import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./ui/styles/globals.css";

const poppins = Poppins({
	weight: ["300", "400", "500", "600", "700"],
	display: "swap",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "MiDoctor",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="es">
			<body className={poppins.className}>{children}</body>
		</html>
	);
}
